### ISSUE TITLE
Excellent pydantic support for sized containers

### ISSUE THREAD

**Issue by antonagestam** [antonagestam/phantom-types#111]
Currently there are two issues:

- [x] ~Pydantic doesn't expose the "sub-field" type to `__modify_schema__` so we can't add e.g. `{items: {"type": "integer"}}` for a `NonEmpty[int]`. See [discussion](https://github.com/samuelcolvin/pydantic/discussions/2902).~ Fixed in https://github.com/samuelcolvin/pydantic/pull/3434.
- [x] The `PhantomSized` type is _"too"_ flexible. Consider adding an intermediary `BoundedSize` or similar that takes class arguments `min`/`max` and reflects that in `minItems`/`maxItems`.

**Comment by flaeppe** [comment]
Not sure if I'm running in to the [mentioned Caveat](https://phantom-types.readthedocs.io/en/stable/pages/pydantic-support.html#caveats) regarding pydantic and `NonEmpty` below? Or is it a separate issue I'm running in to? (Feels a little bit like I'm running in to some problem with sub-field type not being available)

```python
from phantom.sized import NonEmpty
from pydantic import BaseModel

class M(BaseModel):
    x: NonEmpty[list[str]]

M(x=["abc"])
```

This is the error I get:

```
pydantic.error_wrappers.ValidationError: 1 validation error for M
x
  Could not parse phantom.sized.NonEmpty from ['abc'] (type=type_error)
```

**Comment by antonagestam** [comment]
@flaeppe The documented caveat is only regarding JSON schema validation, e.g. `minItems`, `maxItems` and `items.type` aren't automatically set.

I think you will want to use `NonEmpty[str]` and not `NonEmpty[list[str]]`, there's related discussion in this issue: https://github.com/antonagestam/phantom-types/issues/160
