### ISSUE TITLE
Usage with other types with metaclasses / metaclass conflicts

### ISSUE THREAD

**Issue by sobolevn** [antonagestam/phantom-types#127]
While working on #123 and solving a metaclass conflict, I was wondering about potential usage of `phantom` together with `django` / `sqlalchemy` projects that make a heavy use of metaclasses.

For example, this code will produce a metaclass conflict:

```python
from django.db import models

class  User(models.Model):
    is_paid = models.BooleanField(default=False)

def is_paid_user(value: object) -> bool:
    return isinstance(value, User) and value.is_paid

class PaidUser(User, Phantom, predicate=is_paid_user):
    ...  # metaclass conflict
```

Is there any simple way to support this?
We can probably ship some `util` metaclass solver like the one from here: https://stackoverflow.com/a/41266737/4842742

Or at least we can document how to solve this.

**Comment by antonagestam** [comment]
@sobolevn Documenting this could make sense, but at the same time I want to very strongly discourage creating phantom types with mutable bound types. So I wouldn't want to add an example like the one you provided. I guess a section documenting this would have to be pretty involved, perhaps mentioning one of the ways to freeze Django models (I haven't used those). Wdyt?

**Comment by sobolevn** [comment]
> at the same time I want to very strongly discourage creating phantom types with mutable bound types

Yeah, I understand why 🙂 
But, this is a very imprortant thing to document. 
I can create a new issue about it.

> perhaps mentioning one of the ways to freeze Django models (I haven't used those)

Me neither. But, this looks promising: https://pypi.org/project/django-immutablemodel/

Anyways, this was not about mutability, but about metaclass conflicts. There might be other more suitable examples.

**Comment by antonagestam** [comment]
@sobolevn Absolutely, all improvements to the docs are very welcome! 👍 (And thanks for the work you've put in already!) I think mutability warrants its own section, right now it's only briefly mentioned in special places like here: https://phantom-types.readthedocs.io/en/stable/pages/types.html#module-phantom.sized

Perhaps it'd be a good idea to combine these two topics with the [Bounds section](https://phantom-types.readthedocs.io/en/stable/pages/bounds.html) under something like "Composing Types". E.g. a structure like:

- Composing types
  - Bounds
  - Mutability
  - Metaclass conflicts
