### ISSUE TITLE
TypedDict support

### ISSUE THREAD

**Issue by sobolevn** [antonagestam/phantom-types#134]
Right now if you want to write a `TypedDict` that will work with `isinstance` - you need to write:

```python
from typing_extensions import TypedDict

class User(TypedDict):
    name: str
    registered: bool

class UserDictMeta(type):
    def __instancecheck__(cls, arg: object) -> bool:
        return (
            isinstance(arg, dict) and
            # The part below can be really long if `user` has lots of fields
            isinstance(arg.get('name'), str) and
            isinstance(arg.get('registered'), bool)
        )

UserMeta = type('UserMeta', (UserDictMeta, type(TypedDict)), {})

class UserDict(User, metaclass=UserMeta):
    ...

a = {'name': 'sobolevn', 'registered': True}
print(isinstance(a, UserDict))  # True
```

I see that people can benefit from a better API, like:

```python
from phantom.structure import TypedDictWithStructure
from typing_extensions import TypedDict

class User(TypedDict):
    name: str
    registered: bool

class UserDict(User, TypedDictWithStructure):
   ...

a = {'name': 'sobolevn', 'registered': True}
print(isinstance(a, UserDict))  # True
```

Possible problems:
1. #128 
2. `mypy `right now does not allow to call `isinstance` with `TypedDict` subtypes: `error: Cannot use isinstance() with TypedDict type`

What do you think?

**Comment by sobolevn** [comment]
Related https://bugs.python.org/msg399615

**Comment by antonagestam** [comment]
I think this is better solved in a library focused on runtime type checking of `TypedDict`. It doesn't seem like narrowing a dict to a TypedDict can ever be safe (since the dict could be manipulated by another context). I personally have only found `TypedDict` useful for describing i.e. dict literals in config and so I don't find this compelling.
