### ISSUE TITLE
`UK` not accepted as a `CountryCode`

### ISSUE THREAD

**Issue by flaeppe** [antonagestam/phantom-types#225]
I know the official alpha-2 code is `GB` and `UK` is part of the "exceptional reservations" list of `iso3166-1 alpha-2`, but frankly, all addresses in Great Britain have a post code of `UK`.

I think it could be useful to include `UK` as well, in cases where one wants to use e.g. `country: CountryCode` for address validation or the like.

**Comment by antonagestam** [comment]
@flaeppe I don't think I agree with this.

Your proposal completely changes the meaning of the CountryCode type, and I think it'd be very hard to convince me a non standards confirming type is more useful.

An alternative would be to introduce a new type, but I'm not sure what that type should be to fit your usecase. Doesn't addresses usually just have the full name of the country? E.g. "United Kingdom" in your case?

FWIW I believe french is the official international postal language so, technically "La Suède" is as correct as "Sweden" on a parcel sent to Sweden. What I'm trying to get at is that I don't think that it makes sense for the CountryCode type to have the ability to determine whether or not an address country is correct, and I'm not confident such ability fits here. Wdyt? I'm open to further discussion!

**Comment by flaeppe** [comment]
Any additional type feels a bit off.

Think I opened this issue a bit hastily, and indeed one could perhaps go for a verbose value of the code GB to be UK.

What I initially got in trouble with was aligning with other parties. But so, if they claim to follow the iso3166-1 alpha 2 standard there shouldn't really be any problem one have to overcome.
