### ISSUE TITLE
Type of `phantom.iso3166.LiteralAlpha2` is `object`

### ISSUE THREAD

**Issue by flaeppe** [antonagestam/phantom-types#264]
- python: `3.10.2`
- mypy: `0.982`
- phantom-types: `1.1.0`

Repro for above environment running: `mypy --config-file= --strict path/to/contents/below.py`

```python
from phantom.iso3166 import LiteralAlpha2

reveal_type(LiteralAlpha2)  # 3: note: Revealed type is "builtins.object"
```

I would expect it to be a long `Literal` list, or am I wrong?

**Comment by flaeppe** [comment]
Hm, maybe this isn't an issue, since it's a `TypeAlias`. It's just confusing that `reveal_type()` shows `builtins.object` (which I presume is the runtime type of `Literal`). While it still maintains the `Literal`s.

**Comment by flaeppe** [comment]
Aha, I got stuck in this because of a `Unsupported left operand type for | ("object")`. Which appears when using `|` with the `ParsedAlpha2` object. That makes sense, since it doesn't implement the `def __or__` dunder method.

Was kinda looking at this backwards, one can say.

**Comment by antonagestam** [comment]
@flaeppe It seems surprising/weird that the type is `object`, but that's the same for [this example](https://mypy-play.net/?mypy=0.982&python=3.11&gist=b2a85fd3e0a5efe5d833aa053f7a20c1) so probably a red herring. On 1.0.0 the type is `typing._SpecialForm`.

Let me know if you find out more :)
