### ISSUE TITLE
typeguard-3.0.0 seems to break TZAware

### ISSUE THREAD

**Issue by ramnes** [antonagestam/phantom-types#269]
Hey there, thanks for the wonderful library!

I don't have the time to dig much more right now but just as a heads up, typeguard-3.0.0 seems to break TZAware.

Our CI started failing between yesterday and today and the only library that got updated was typeguard, which is only pulled by phantom-types in our case.

Here's what FastAPI + Pydantic gives us with typeguard-3.0.0:

```json
{
  "detail": [
    {
      "loc": [
        "body",
        "startsAt"
      ],
      "msg": "Value is not within bound of 'str': '2023-03-15T19:53:09.772675+00:00'",
      "type": "type_error.bound"
    },
    {
      "loc": [
        "body",
        "endsAt"
      ],
      "msg": "Value is not within bound of 'str': '2023-03-15T20:53:09.772675+00:00'",
      "type": "type_error.bound"
    }
  ]
}
```

**Comment by antonagestam** [comment]
@ramnes Thanks for reporting this. It looks like typeguard 3.0.0 has a flurry of breaking changes. I'll make sure to get a version of phantom-types out that pins to <3 (less than 3, not a heart 😅) ASAP. 

I'll then look into supporting version 3+. Specifically the behavior change to no longer check all items of collections by default looks problematic, and makes me wonder whether the exposed API is thread safe.

**Comment by antonagestam** [comment]
If you feel like working on the quick-fix (pin typeguard + bump patch version), that could help getting a fix out slightly faster, otherwise I'll get to it by end of today hopefully.

**Comment by ramnes** [comment]
There you go: #270 :)

**Comment by antonagestam** [comment]
FYI, I raised the issue about thread safety with the new typeguard global config: https://github.com/agronholm/typeguard/issues/316
