### ISSUE TITLE
Datetime section empty in documentation

### ISSUE THREAD

**Issue by enadeau** [antonagestam/phantom-types#276]
I came accross your project and was looking at the doc and there seems to be that the  `types > datetime` section is accidentally empty. I don,t know anything about the project but I thought I'd would be nice to let you know.

![image](https://github.com/antonagestam/phantom-types/assets/12940089/a2a9dfe2-ac76-41af-9bff-432e91fe5687)

**Comment by antonagestam** [comment]
Thanks for reporting this, and sorry for the radio silence, I've been a bit low on bandwidth for OSS.

This is now fixed by these PRs:

- https://github.com/antonagestam/phantom-types/pull/280
- https://github.com/antonagestam/phantom-types/pull/279

I'll make a patch release to get docs in sync.
