### ISSUE TITLE
Incompatibility with `NewType`

### ISSUE THREAD

**Issue by akefirad** [antonagestam/phantom-types#296]
Is this a bug or feature:
```python
MoneyAmount = NewType("MoneyAmount", Natural)
```
Calling the `parse` method of `MoneyAmount` fails with
```
 AttributeError: 'NewType' object has no attribute 'parse'
```
Any way to make phantom types compatible with `NewType`?
Thanks.

**Comment by antonagestam** [comment]
> Is this a bug or feature?

Neither, `NewType` is a completely distinct feature from this library. You could say it's a _feature of NewTypes_ that they work this way though.

A better way to look at it is that phantom types are a more powerful alternative than new types. I've written [this blog post](https://www.agest.am/phantom-types-in-python) that discusses some related things.

**Comment by antonagestam** [comment]
If you want the resulting type to have the parse method, what you should do rather than using NewType is likely this:

```python
class MoneyAmount(Natural): ...
```
