### ISSUE TITLE
Support numeric tower in phantom.numeric

### ISSUE THREAD

**Issue by antonagestam** [antonagestam/phantom-types#34]
See https://github.com/python/mypy/issues/3186

**Comment by posita** [comment]
I don't know much about your use case (of if you even consider this an issue worth pursuing now), but you might want to see if [``numerary``](/posita/numerary) can help you. If [this journey](https://posita.github.io/numerary/latest/whytho/) lines up with your own, ``numerary`` could be an intermediary solution until python/mypy#3186 is fixed. (Alternatively, the techniques used therein might provide inspiration if you can't take a dependency.) Happy to [consult here](https://github.com/posita/numerary/discussions), if helpful. Apologies for the interruption if this is a distraction for you.

**Comment by antonagestam** [comment]
@posita Hey, it's a distraction for sure, but a good one! I'll look into it as soon as I get the time. The issue here is I would really like to allow using any "numerics", but because of the current situation I just went with `int | float` for now: https://github.com/antonagestam/phantom-types/blob/main/src/phantom/interval.py#L52

Thanks for reaching out 👍

**Comment by antonagestam** [comment]
And most of these functions should support any numerics too: https://github.com/antonagestam/phantom-types/blob/main/src/phantom/predicates/numeric.py
